### PR TITLE
Fix crashes related to Eureka library

### LINKED ISSUE #89: EXC_BAD_ACCESS Crash with latest XCode Version
@florianpreknya : Is this just a local problem on my machine? This happens on the latest tag V2.7.4.512 and on the master, too.

If I update Eureka to the latest release, the app starts fine, but looks like Eureka now makes other problems. Maybe it would be nice to get Eureka to the latest version.

### PR DESCRIPTION
**Pull request by florianpreknya**
Fixes #89

### CODE REVIEW

File: nightguard/PrefsViewController.swift [hunk 1]
```diff
@@ -89,7 +89,8 @@ class PrefsViewController: CustomFormViewController {
                             let rows = CGFloat(title.count / 50) + 1 // we condiser 80 characters are on a line
                             $0.cell.height = { 30 * rows }
                         }
-                        row.section?.insert(labelRow, at: row.indexPath!.row + index + 1)
+                        let insertionRow = row.indexPath!.row + index + 1
```
Comment (dhermanns) [inline nightguard/PrefsViewController.swift:92]: Looks pretty the same for me - did this cause any problems? Or just clean up?
